name: Go-Core Executable Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  central-pipeline:
    uses: AeonDigital/Go-Core-Template-CI-CD/.github/workflows/ci-cd.yaml@main
